name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - plotly
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-tibble
  - r-readr
  - r-purrr
  - r-stringr
  - r-forcats
  - r-plotly
  - r-sf
  - r-leaflet
  - r-tmap
  - r-sp
  - r-rcpp
