name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9  # specify the Python version you need
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - plotly
  - r-base  # Include R base to ensure R support
  - r-irkernel  # R kernel for Jupyter
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-shiny
  - r-leaflet
  - r-sf
  - r-units
  - r-plotly
  - gdal  # System dependency for R sf package
  - proj  # System dependency for R sf package
  - geos  # System dependency for R sf package
  - libiconv  # Ensure libiconv is installed for locale support
  - libudunits2